name:                Fileserver
version:             0.1.0.0
github:              "Swordlash/Fileserver"
license:             BSD3
author:              "Mateusz Goślinowski"
maintainer:          "mateusz.goslinowski@gmail.com"
copyright:           "2020 Mateusz Goślinowski"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Swordlash/Fileserver#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- servant-conduit
- wai
- warp
- cryptonite
- conduit
- acid-state
- text
- path
- ixset-typed
- safecopy
- mtl
- filepath
- record-hasfield
- directory
- optparse-applicative
- interpolatedstring-perl6
- protolude
- unliftio
- extra
- servant-blaze
- blaze-markup
- blaze-html

default-extensions:
- OverloadedStrings
- OverloadedLists
- DataKinds
- PolyKinds
- MultiParamTypeClasses
- FunctionalDependencies
- FlexibleInstances
- UndecidableInstances
- LambdaCase
- NamedFieldPuns
- RecordWildCards
- TypeApplications
- TypeFamilies
- TypeOperators
- RankNTypes
- ScopedTypeVariables
- TemplateHaskell
- DeriveGeneric
- DeriveDataTypeable
- DeriveAnyClass
- DerivingStrategies
- DuplicateRecordFields
- GeneralizedNewtypeDeriving
- QuasiQuotes
- NoImplicitPrelude
- TupleSections

library:
  source-dirs: .

executables:
  fileserver:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wextra
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    dependencies:
    - base
    - Fileserver

tests:
  fileserver-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - Fileserver
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
